development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: sweetguy30@gmail.com
  :password: 4ad3d1311
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: sweetguy30@gmail.com
  :password: 4ad3d1311
  :enable_starttls_auto: true